POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "bro",
    "number": "123-1234567"
}

# Response:
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 58
# ETag: W/"3a-u+nngVhlKtNB8MRuanbcgP2nnsI"
# Date: Thu, 12 Sep 2024 21:29:51 GMT
# Connection: close
# 
# {
#   "name": "sample Name",
#   "number": "123-4458",
#   "id": 3317251821
# }

# http://localhost:3001/api/persons shows that the entry has been added

# for (bad number):
# {
#     "name": "bro",
#     "number": "123-1234567"
# }
# Failing Response: 
# HTTP/1.1 400 Bad Request
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 86
# ETag: W/"56-O+s4DNGYX5h8CwgyZTG3wdV9jGQ"
# Date: Sat, 14 Sep 2024 18:27:36 GMT
# Connection: close
# 
# {
#   "error": "Person validation failed: number: 123-1234567 is not a valid phone number!"
# }